### ISSUE TITLE
How to disable rke2 snapshot controller charts

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rke2-docs#123]
Since Kubernetes version 1.25 there are 3 new charts for the snapshot-controller. Our docs are not updated reflecting just [canal,coredns,ingres and metric-server](https://docs.rke2.io/advanced?_highlight=disable#disabling-server-charts) and it would be nice to include these charts also.

**Comment by brandond** [comment]
Ref: https://github.com/rancher/rke2/issues/5061#issuecomment-1819679759
