### ISSUE TITLE
Update docs to provide firewalling advice/guidance

### ISSUE THREAD

**Issue by Daemonslayer2048** [rancher/rke2-docs#160]
## Summary  
RKE2 docs suggest disabling firewalld (location: [here](https://docs.rke2.io/known_issues?_highlight=firewalld#firewalld-conflicts-with-default-networking)). While this is valid advice, I have come across many users who think RKE2 in general is incompatible with firewalld because of this section alone.   
RKE2 is intended to be a more security focused k8s distro, as such I think given Canal is the default CNI some guidance should be provided on mitigating risks either by pointing users to a CNI that is compatible with firewalld (cilium with eBPF?), or with some custom iptable rules as a starting point (not my preferred solution).

## Potential solutions 
If my understanding is correct, cilium with eBPF enabled on RKE2 should be compatible with firewalld. If my understanding is correct that could be listed as a mitigation.   
I also know while not supported, iptable rules can be set manually and should work, again I know its not supported but some guidance is needed. This way if Canal is still the preferred CNI of a user they can be informed that manual rules can work (at their own risk).

**Comment by brandond** [comment]
> I have come across many users who think RKE2 in general is incompatible with firewalld because of this section alone.

That is intended to be the key takeaway, yes. We recommend that it be disabled. If you chose to leave it running, and poke holes as the documentation describes, you are doing so at your own risk.

**Comment by Daemonslayer2048** [comment]
What part of the docs are you referring to when you say: "If you chose to leave it running, and poke holes as the documentation describes"

**Comment by brandond** [comment]
By opening up the ports listed at https://docs.rke2.io/install/requirements#inbound-network-rules. K3s provides some suggested firewall-cmd invocations to open things up at https://docs.k3s.io/installation/requirements#operating-systems, but we don't provide similar suggestions for RKE2.

**Comment by mdgraboski** [comment]
> > I have come across many users who think RKE2 in general is incompatible with firewalld because of this section alone.
> 
> That is intended to be the key takeaway, yes. We recommend that it be disabled. Most CNI projects do not support use with firewalld or ufw enabled, and we inherit that position from them. If you chose to leave it running, and poke holes as the documentation describes, you are doing so at your own risk.

Could you provide more information on the security implications of disabling firewalld on your RKE2 cluster? How do I protect my nodes from network ingress that I specifically do not want (e.g., inbound requests originating from the internet)?
