### ISSUE TITLE
Links release notes mixed

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rke2-docs#161]
Hi there,
The links for the charts are mixed in the Release note for the kubernetes versions. As an example,
**Version 1.26**
The link https://docs.rke2.io/release-notes/v1.26.X has some hyperlinks wrong. For instance, for v1.26.10,(https://docs.rke2.io/release-notes/v1.26.X), under the ingress column, the chart redirects to COREDNS [v1.10.1](https://github.com/coredns/coredns/releases/tag/v1.10.1), same situation with rke2-coredns columns which point to the metric-servers and so on.

**Comment by dereknola** [comment]
https://github.com/rancher/rke2-docs/pull/140 Messed up the column names, IDK why.

**Comment by dereknola** [comment]
https://github.com/rancher/rke2-docs/pull/162 Fixes it.
