### ISSUE TITLE
Allow for sqlite installs in k3s

### ISSUE THREAD

**Issue by rancher-max** [rancher/rke2-docs#208]
When installing a single server, we should allow to NOT pass `cluster-init` and not have any datastore endpoint so that we use kine with sqlite.

**Comment by brandond** [comment]
Are we doing this as `--cluster-init=false`, or as `--datastore-endpoint=sqlite://`?

**Comment by rancher-max** [comment]
Oops I created this issue in the wrong repo 🙈 This was meant for our automation where we do HA only currently
