### ISSUE TITLE
Rke2 etcd restore fails if token is not provided

### ISSUE THREAD

**Issue by mrolmedo** [rancher/rke2-docs#285]
Hi team,
Based on this thread https://github.com/rancher/rke2/discussions/4036#discussioncomment-5373033 and SURE-9356, the rke2-restore  process should be updated accordingly.

**Comment by brandond** [comment]
It is only necessary if the token is not present on disk, or the token on disk differs from the token in use when the snapshot was taken. The token is written to disk by rke2 when it starts, so if you're restoring a snapshot previously taken on the same cluster, it is not generally necessary to manually pass the token. 

We should cover that in the docs though. For both rke2 and k3s.

**Comment by brandond** [comment]
We do call it out at the top of every release note:
https://github.com/rancher/rke2/releases/tag/v1.30.6%2Brke2r1

But yes, docs site also would be good.

**Comment by mrolmedo** [comment]
Docs updated:) 
Thanks
