### ISSUE TITLE
Need to document steps for manual CA certificate generation / rotation

### ISSUE THREAD

**Issue by brandond** [rancher/rke2-docs#59]
We need to document the steps to manually pre-generate CA certs + keys, or update the expiration on existing certs to extend the expiration. Ideally we would also output the CA hash in a format compatible with the `--token` arg ("K10" + SHA256 sum of cert bytes).

We don't currently have any documentation on how to do this for either k3s or rke2, but there are some good starting points at:
* https://github.com/rancher/k3s/issues/1868#issuecomment-639690634
* https://github.com/rancher/k3s/issues/2342#issuecomment-703879154

One important note is that the hash we are using is a SH256 sum of the server's certificate, NOT its public key. This means that any changes to the cert, including extending its expiration, will change the hash and require passing a new `--token` to joining clients if they are to trust it.

gz#13930
gz#15095
gz#16112

**Comment by dereknola** [comment]
Addressed by https://github.com/rancher/rke2-docs/pull/101
