### ISSUE TITLE
Update the RKE2 cluster reset procedure to include the backup and delete of db files.

### ISSUE THREAD

**Issue by vincebrannon** [rancher/rke2-docs#77]
When running the reset as defined here:
https://docs.rke2.io/backup_restore#cluster-reset

You are instructed to backup and delete some db files as part of the output in the CLI then rerun the command without the flag and rejoin nodes. 

Would be nice to have this step documented.

**Comment by dereknola** [comment]
This is already given in the existing instructions: https://docs.rke2.io/backup_restore?_highlight=rm&_highlight=rf#restoring-a-snapshot-to-existing-nodes
