### ISSUE TITLE
STIG default umask of 077 and CIS-1.23 prevents etcd from starting

### ISSUE THREAD

**Issue by dajester2013** [rancher/rke2-docs#80]
Something to consider for the "Known Issues", or the "Hardening Guide", as discovered in https://github.com/rancher/rke2/issues/4313, if running with the cis-1.23 profile, and in a STIG'd RHEL environment, you must set the umask to 022 before running any `rke2` binary commands (`rke2 server`, `rke2 server --cluster-reset`, etc).  It is also suggested to set the umask to 022 in the systemd unit file.

**Comment by brooksphilip** [comment]
@dajester2013  reaching out to you on Rancher Users Slack

**Comment by vincebrannon** [comment]
SURE-6932
