### ISSUE TITLE
kubeapi server arg incorrect

### ISSUE THREAD

**Issue by jcox10** [rancher/rke2-docs#88]
In https://github.com/rancher/rke2-docs/edit/main/docs/security/pod_security_standards.md it states that:
> If you want to override the default pod security standard configuration file, you can pass `pod-security-admission-config-file:` <path-to-custom-psa-config-file> to the RKE2 config file.

This is incorrect, the argument per [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller) is `admission-control-config-file`.

**Comment by brandond** [comment]
The docs are correct, but I think you're misunderstanding them.

RKE2's `pod-security-admission-config-file` cli flag or config file key is passed through to the `admission-control-config-file` flag on the apiserver. It is equivalent to setting `kube-apiserver-arg=admission-control-config-file=/path/to/file`, although doing that instead will bypass some other RKE2-specific logic that wants to know where the admission control config file is located - so I wouldn't recommend doing that.

**Comment by jcox10** [comment]
Ah yes, I thought the rke2 docs were saying to pass the argument directly to the apiserver with `kube-apiserver-arg`. I'll pass it directly to rke2. Thanks!
